apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ldap-data-pvc
    namespace: {{ .Values.namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.storage.data.size }}
    storageClassName: {{ .Values.storage.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ldap-config-pvc
    namespace: {{ .Values.namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.storage.config.size }}
    storageClassName: {{ .Values.storage.storageClassName }}
