apiVersion: v1
kind: Service
metadata:
    name: openldap
    namespace: {{ .Values.namespace }}
spec:
    type: NodePort
    selector:
        app: openldap
    ports:
        - name: ldap
          port: 389
          targetPort: 389
          nodePort: {{ .Values.nodePorts.ldap }}
        - name: ldaps
          port: 636
          targetPort: 636
          nodePort: {{ .Values.nodePorts.ldaps }}
